// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-WtV7VfkGeGMEB5CLwE-89kmjDC7Glkw',
    appId: '1:469979500149:web:9a2e27e63c772e6f91323c',
    messagingSenderId: '469979500149',
    projectId: 'fluttercanteenapp',
    authDomain: 'fluttercanteenapp.firebaseapp.com',
    storageBucket: 'fluttercanteenapp.appspot.com',
    measurementId: 'G-K7WRYDXDEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_5wECr4Rl5oSKqM91S0gYT5FkkSUTxE',
    appId: '1:469979500149:android:21b938f708e82fa891323c',
    messagingSenderId: '469979500149',
    projectId: 'fluttercanteenapp',
    storageBucket: 'fluttercanteenapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsei_krY5HZAuizCdx6OpvextZ_51VoPI',
    appId: '1:469979500149:ios:59b1100c454d714391323c',
    messagingSenderId: '469979500149',
    projectId: 'fluttercanteenapp',
    storageBucket: 'fluttercanteenapp.appspot.com',
    iosBundleId: 'com.example.fluttercanteenapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsei_krY5HZAuizCdx6OpvextZ_51VoPI',
    appId: '1:469979500149:ios:59b1100c454d714391323c',
    messagingSenderId: '469979500149',
    projectId: 'fluttercanteenapp',
    storageBucket: 'fluttercanteenapp.appspot.com',
    iosBundleId: 'com.example.fluttercanteenapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-WtV7VfkGeGMEB5CLwE-89kmjDC7Glkw',
    appId: '1:469979500149:web:adf1ec5c538f4fcb91323c',
    messagingSenderId: '469979500149',
    projectId: 'fluttercanteenapp',
    authDomain: 'fluttercanteenapp.firebaseapp.com',
    storageBucket: 'fluttercanteenapp.appspot.com',
    measurementId: 'G-3L59EPB56Q',
  );
}
